Repository wecode-bootcamp-korea/40-2nd-ICE-CREAM-frontend, pull requests merged in 2022-12, with the labels that each got.

#3 [40기 김태윤] ADD : Footer 레이아웃
  src/components/Footer/Footer.js
Labels: 완료

#1 [40기 김태윤] ADD : Nav 레이아웃 구현
  src/components/Nav/Nav.js
Labels: 수정 요청

#6 [40기 김태윤] ADD : Mixin
  src/styles/mixin.js
Labels: 멘토 리뷰 요청

#8 [40기 김태윤] MODFIY : nav fixed, z-index 추가
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Signin/Signin.js
  src/styles/theme.js
Labels: 완료

#10 [40기 김태윤] ADD : 폰트 추가
  src/styles/GlobalStyle.js
Labels: 완료

#5 [40기 김태윤] ADD : detail페이지
  package-lock.json
  package.json
  src/components/Nav/Nav.js
  src/hooks/useOutSideClick.js
  src/pages/Detail/AlertModal.js
  src/pages/Detail/Carousel.js
  src/pages/Detail/ChartLine.js
  src/pages/Detail/ChartSection.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Dropdown.js
  src/pages/Detail/FloatingPrice.js
  src/pages/Detail/MoreModal.js
  src/pages/Detail/chartData.js
  src/pages/Detail/components/BuyButton.js
  src/pages/Detail/components/SellButton.js
  src/pages/Detail/style.css
  src/styles/theme.js
Labels: 완료

#7 [40기 문다연] ADD: Signup 레이아웃 구현
  .env.sample
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/pages/KakaoLogin/KakaoLogin.js
  src/pages/Signup/Signup.js
Labels: 완료

#11 [40기 문다연] ADD: Style 페이지 구현
  .gitignore
  public/data/data.json
  src/pages/Style/Style.js
Labels: 멘토 리뷰 요청

#4 [40기 서혜선] ADD: 메인페이지 레이아웃 구현
  package-lock.json
  package.json
  public/data/productData.json
  src/pages/Main/Main.js
  src/pages/Main/MainCarousel/MainCarousel.js
  src/pages/Main/MainProduct/MainProduct.js
  src/pages/Main/MainReuse/MainReuse.js
  src/pages/Main/MainShortCutItem/MainShortCutItem.js
Labels: 멘토 리뷰 요청

#9 [40기 서혜선] ADD: 리스트페이지
  src/pages/Shop/Shop.js
  src/pages/Shop/ShopProduct/ShopProduct.js
Labels: 멘토 리뷰 요청
