Repository wecode-bootcamp-korea/40-2nd-ICE-CREAM-frontend, pull requests merged in 2023-01, with the labels that each got.

#18 [40기 김태윤] MODIFY : footer 상호명 변경
  src/components/Footer/Footer.js
Labels: 멘토 리뷰 요청

#12 [40기 김태윤] ADD : detail 페이지
  public/data/chartData.json
  public/data/chartTotalData.json
  src/config/config.js
  src/pages/Detail/AlertModal.js
  src/pages/Detail/Carousel.js
  src/pages/Detail/ChartLine.js
  src/pages/Detail/ChartSection.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Dropdown.js
  src/pages/Detail/MoreModal.js
Labels: 완료

#16 [40기 김태윤] ADD : 사이즈선택 페이지, 구매, 판매 페이지
  src/Router.js
  src/pages/BuySell/Buy.js
  src/pages/BuySell/BuySelect.js
  src/pages/BuySell/BuySellLayout.js
  src/pages/BuySell/DealAlertModal.js
  src/pages/BuySell/SelectLayout.js
  src/pages/BuySell/Sell.js
  src/pages/BuySell/SellSelect.js
  src/pages/Detail/Detail.js
  src/pages/Detail/chartData.js
  src/pages/Detail/components/BuyButton.js
  src/pages/Detail/components/SellButton.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청, 완료

#19 [40기 김태윤] ADD : nav 로고 링크 추가
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#20 [40기 문다연] ADD: Style 페이지 구현
  public/data/StyleData.json
  src/Router.js
  src/pages/BuySell/DealBidModal.js
  src/pages/Style/Card.js
  src/pages/Style/Style.js
  src/pages/StyleDetail/StyleCard.js
  src/pages/StyleDetail/StyleDetail.js
Labels: 완료

#24 [40기 김태윤] ADD : 로그아웃 로직 추가
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#23 [40기 김태윤] Update README.md
  README.md
Labels: 멘토 리뷰 요청

#17 [40기 서혜선] Add: main, shop 페이지 무한스크롤 기능 추가
  public/data/productData.json
  src/Router.js
  src/pages/Main/Main.js
  src/pages/Main/MainCarousel/MainCarousel.js
  src/pages/Main/MainProduct/MainProduct.js
  src/pages/Main/MainReuse/MainReuse.js
  src/pages/Main/ShortCutItem/ShortCutItem.js
  src/pages/Shop/AsideCategory/AsideCategory.js
  src/pages/Shop/Shop.js
  src/pages/Shop/ShopProduct/ShopProduct.js
  src/utils/queryString.js
Labels: 멘토 리뷰 요청
